# Site settings
author: William Wedderburn
title: “Why did you decide to study Software Engineering?”
header-img: img/home-bg.png
email: wedderburn95@yahoo.com
copyright_name: William Wedderburn
description: > # this means to ignore newlines until "baseurl:"
  Coding is the future
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wedderburn95

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
